### ISSUE TITLE
generate fr and de - 1077

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/cloud_volumes#182]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by netapp-gudugunti** [comment]
Although the build is a "success," site is not up.
BPR and labels are set.

**Comment by ntap-bmegan** [comment]
There's no English site either: https://docs.netapp.com/us-en/cloud_volumes/index.html

@netapp-bcammett - Can you refresh my memory on what's up with this repo set? We have repos but no sites. 

![image](https://user-images.githubusercontent.com/56453501/202487764-8d0f3789-3896-454f-b2b9-5ea2d3d1b0d0.png)

**Comment by netapp-bcammett** [comment]
I believe this was the repo for Cloud Volumes Service for AWS which is now defunct. @netapp-tonacki, do I have that right?

**Comment by netapp-tonacki** [comment]
CVS for AWS still exists: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-service-aws/index.html

Not sure what that other repo is.

**Comment by akseldavis** [comment]
The `cloud_volumes` repository is the original CVS repository that was supposed to maintain AWS, Azure, and GCP. Obviously, that has now shifted over the past 4 years, however, they used the "subfolder" approach, and so the actual site for AWS is https://docs.netapp.com/us-en/cloud_volumes/aws/. There is no top level landing page for this site since it was originally designed for the subfolder approach. Non-EN sites also appear to be working with the `/aws/` path. 

My larger concern is that the new site that Ben shared appears on first glance to be duplicate content. Can we get clarity @netapp-tonacki or @netapp-bcammett on the differences. My apologies if this is the 5th time you've explained it to me. 

- Site 1: https://docs.netapp.com/us-en/cloud_volumes/aws/index.html
- Site 2: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-service-aws/index.html

**Comment by netapp-bcammett** [comment]
Site 1 is for managing Cloud Volumes Service natively from the AWS side (it's no longer available for new customers)

Site 2 is for managing Cloud Volumes Service from the NetApp side via BlueXP (ditto)

So they are two completely different sites for the same service, but using two different management interfaces (one on the AWS side and one on the NetApp side).

Both of those doc sites should go away eventually (not sure when).

**Comment by akseldavis** [comment]
Thanks for the reminder, Ben! For the purposes of this thread the CVS for AWS (native) is working as expected with new languages enabled. Both of the sites identified should be considered in a separate conversation for being removed/decommissioned.

**Comment by ntap-bmegan** [comment]
Going back to this repo set, `cloud_volumes`, which does not generate any websites... Is this as expected? Should these repos be archived?

**Comment by akseldavis** [comment]
@ntap-bmegan The `cloud_volumes` repository does generate websites, but they start at the `/aws/` path because there is no root-level `index.html` page. 

- **EN Site:** https://docs.netapp.com/us-en/cloud_volumes/aws/index.html
- **Hosted deliverable:** https://github.com/NetappDocs/cloud_volumes/tree/gh-pages

Inside the hosted deliverable you will also see GCP and ANF resources which I believe are linked to from other site locations.

**Comment by ntap-bmegan** [comment]
@netapp-gudugunti - Go ahead and finish up any remaining configuration and close. The French and German sites are available from the link @akseldavis provided.

**Comment by netapp-gudugunti** [comment]
Total TOT: 30 minutes.

**Comment by dmajones** [comment]
> @ntap-bmegan The `cloud_volumes` repository does generate websites, but they start at the `/aws/` path because there is no root-level `index.html` page.
> 
> * **EN Site:** https://docs.netapp.com/us-en/cloud_volumes/aws/index.html
> * **Hosted deliverable:** https://github.com/NetappDocs/cloud_volumes/tree/gh-pages
> 
> Inside the hosted deliverable you will also see GCP and ANF resources which I believe are linked to from other site locations.

@akseldavis For all sites that have a public website we are adding the "published" topic to the repo, but per the thread above, this repo seems to be a special case. Can you advise regarding how this repo should be tagged (as it relates to the topic (published)?
